### ISSUE TITLE
--test Error

### ISSUE THREAD

**Issue by liusiyu1** [kisselz/redactable-sigs#7]
=== ECC Accumulator ===
Exception in thread "main" java.lang.NoClassDefFoundError: it/unisa/dia/gas/plaf/jpbc/pairing/PairingFactory
	at crypto.accumulator.ECCAccumulator.<init>(ECCAccumulator.java:63)
	at cli.Test.runECCAccumulatorTest(Test.java:243)
	at cli.Test.testCore(Test.java:50)
	at cli.Main.processCommand(Main.java:766)
	at cli.Main.main(Main.java:793)
Caused by: java.lang.ClassNotFoundException: it.unisa.dia.gas.plaf.jpbc.pairing.PairingFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 5 more

**Comment by liusiyu1** [comment]
Secceed. Move pairing.params to dist.
